# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_minder2_murmur/database.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_minder2_murmur import docker_pb2 as grpc__minder2__murmur_dot_docker__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_minder2_murmur/database.proto',
  package='grpc_minder2_murmur.database',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"grpc_minder2_murmur/database.proto\x12\x1cgrpc_minder2_murmur.database\x1a grpc_minder2_murmur/docker.proto\"z\n\x11\x44\x61tabaseContainer\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12\x0f\n\x07network\x18\x03 \x01(\t\x12\x32\n\x05ports\x18\x04 \x03(\x0b\x32#.grpc_minder2_murmur.docker.PortMap\"t\n\x0e\x44\x65stroyRequest\x12\x42\n\tcontainer\x18\x01 \x01(\x0b\x32/.grpc_minder2_murmur.database.DatabaseContainer\x12\x0f\n\x07volumes\x18\x02 \x01(\x08\x12\r\n\x05\x66orce\x18\x03 \x01(\x08\x62\x06proto3')
  ,
  dependencies=[grpc__minder2__murmur_dot_docker__pb2.DESCRIPTOR,])




_DATABASECONTAINER = _descriptor.Descriptor(
  name='DatabaseContainer',
  full_name='grpc_minder2_murmur.database.DatabaseContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_id', full_name='grpc_minder2_murmur.database.DatabaseContainer.server_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='grpc_minder2_murmur.database.DatabaseContainer.image', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='network', full_name='grpc_minder2_murmur.database.DatabaseContainer.network', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ports', full_name='grpc_minder2_murmur.database.DatabaseContainer.ports', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=224,
)


_DESTROYREQUEST = _descriptor.Descriptor(
  name='DestroyRequest',
  full_name='grpc_minder2_murmur.database.DestroyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container', full_name='grpc_minder2_murmur.database.DestroyRequest.container', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volumes', full_name='grpc_minder2_murmur.database.DestroyRequest.volumes', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='force', full_name='grpc_minder2_murmur.database.DestroyRequest.force', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=342,
)

_DATABASECONTAINER.fields_by_name['ports'].message_type = grpc__minder2__murmur_dot_docker__pb2._PORTMAP
_DESTROYREQUEST.fields_by_name['container'].message_type = _DATABASECONTAINER
DESCRIPTOR.message_types_by_name['DatabaseContainer'] = _DATABASECONTAINER
DESCRIPTOR.message_types_by_name['DestroyRequest'] = _DESTROYREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DatabaseContainer = _reflection.GeneratedProtocolMessageType('DatabaseContainer', (_message.Message,), dict(
  DESCRIPTOR = _DATABASECONTAINER,
  __module__ = 'grpc_minder2_murmur.database_pb2'
  # @@protoc_insertion_point(class_scope:grpc_minder2_murmur.database.DatabaseContainer)
  ))
_sym_db.RegisterMessage(DatabaseContainer)

DestroyRequest = _reflection.GeneratedProtocolMessageType('DestroyRequest', (_message.Message,), dict(
  DESCRIPTOR = _DESTROYREQUEST,
  __module__ = 'grpc_minder2_murmur.database_pb2'
  # @@protoc_insertion_point(class_scope:grpc_minder2_murmur.database.DestroyRequest)
  ))
_sym_db.RegisterMessage(DestroyRequest)


# @@protoc_insertion_point(module_scope)
