# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_minder2_murmur/docker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n grpc_minder2_murmur/docker.proto\x12\x1agrpc_minder2_murmur.docker\"9\n\x07PortMap\x12\x16\n\x0e\x63ontainer_port\x18\x01 \x01(\t\x12\x16\n\x0epublished_port\x18\x02 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_minder2_murmur.docker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PORTMAP._serialized_start=64
  _PORTMAP._serialized_end=121
# @@protoc_insertion_point(module_scope)
