# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_minder2_murmur/docker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_minder2_murmur/docker.proto',
  package='grpc_minder2_murmur.docker',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n grpc_minder2_murmur/docker.proto\x12\x1agrpc_minder2_murmur.docker\"9\n\x07PortMap\x12\x16\n\x0e\x63ontainer_port\x18\x01 \x01(\t\x12\x16\n\x0epublished_port\x18\x02 \x01(\rb\x06proto3')
)




_PORTMAP = _descriptor.Descriptor(
  name='PortMap',
  full_name='grpc_minder2_murmur.docker.PortMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_port', full_name='grpc_minder2_murmur.docker.PortMap.container_port', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='published_port', full_name='grpc_minder2_murmur.docker.PortMap.published_port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['PortMap'] = _PORTMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PortMap = _reflection.GeneratedProtocolMessageType('PortMap', (_message.Message,), dict(
  DESCRIPTOR = _PORTMAP,
  __module__ = 'grpc_minder2_murmur.docker_pb2'
  # @@protoc_insertion_point(class_scope:grpc_minder2_murmur.docker.PortMap)
  ))
_sym_db.RegisterMessage(PortMap)


# @@protoc_insertion_point(module_scope)
