# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_minder2_murmur/main.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_minder2_murmur import murmur_pb2 as grpc__minder2__murmur_dot_murmur__pb2
from grpc_minder2_murmur import database_pb2 as grpc__minder2__murmur_dot_database__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1egrpc_minder2_murmur/main.proto\x12\x13grpc_minder2_murmur\x1a grpc_minder2_murmur/murmur.proto\x1a\"grpc_minder2_murmur/database.proto\"\x06\n\x04Void2\x99\x02\n\rMurmurService\x12P\n\x06\x43reate\x12+.grpc_minder2_murmur.murmur.MurmurContainer\x1a\x19.grpc_minder2_murmur.Void\x12P\n\x07\x44\x65stroy\x12*.grpc_minder2_murmur.murmur.DestroyRequest\x1a\x19.grpc_minder2_murmur.Void\x12\x64\n\x08GetImage\x12+.grpc_minder2_murmur.murmur.MurmurContainer\x1a+.grpc_minder2_murmur.murmur.MurmurContainer2\xbb\x01\n\x0f\x44\x61tabaseService\x12T\n\x06\x43reate\x12/.grpc_minder2_murmur.database.DatabaseContainer\x1a\x19.grpc_minder2_murmur.Void\x12R\n\x07\x44\x65stroy\x12,.grpc_minder2_murmur.database.DestroyRequest\x1a\x19.grpc_minder2_murmur.Voidb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_minder2_murmur.main_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOID._serialized_start=125
  _VOID._serialized_end=131
  _MURMURSERVICE._serialized_start=134
  _MURMURSERVICE._serialized_end=415
  _DATABASESERVICE._serialized_start=418
  _DATABASESERVICE._serialized_end=605
# @@protoc_insertion_point(module_scope)
