# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_minder2_murmur/murmur.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_minder2_murmur import docker_pb2 as grpc__minder2__murmur_dot_docker__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n grpc_minder2_murmur/murmur.proto\x12\x1agrpc_minder2_murmur.murmur\x1a grpc_minder2_murmur/docker.proto\"x\n\x0fMurmurContainer\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12\x0f\n\x07network\x18\x03 \x01(\t\x12\x32\n\x05ports\x18\x04 \x03(\x0b\x32#.grpc_minder2_murmur.docker.PortMap\"p\n\x0e\x44\x65stroyRequest\x12>\n\tcontainer\x18\x01 \x01(\x0b\x32+.grpc_minder2_murmur.murmur.MurmurContainer\x12\x0f\n\x07volumes\x18\x02 \x01(\x08\x12\r\n\x05\x66orce\x18\x03 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_minder2_murmur.murmur_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MURMURCONTAINER._serialized_start=98
  _MURMURCONTAINER._serialized_end=218
  _DESTROYREQUEST._serialized_start=220
  _DESTROYREQUEST._serialized_end=332
# @@protoc_insertion_point(module_scope)
